# As of Symfony 5.1, deprecations are logged in the dedicated "deprecation" channel when it exists
#monolog:
#    channels: [deprecation]
#    handlers:
#        deprecation:
#            type: stream
#            channels: [deprecation]
<<<<<<< HEAD
#            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
=======
#            path: php://stderr
>>>>>>> 1043305e0bd1fd20d7bed96660b3895f2d22e5ae
